apiVersion: apps/v1
kind: Deployment
metadata:
  name: bo-app
  labels:
    app: bo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bo-app
  template:
    metadata:
      labels:
        app: bo-app
    spec:
      containers:
        - name: bo-app
          image: 471112722662.dkr.ecr.us-east-1.amazonaws.com/bo:latest     # Add config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bo-service
spec:
  selector:
    app: bo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
