name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Source Code Testing
        run: |
          # Run linting
          npm run lint          

      - name: Build Docker Image               #add config
        run: |
          docker build -t bo .
          docker tag bo:latest 471112722662.dkr.ecr.us-east-1.amazonaws.com/bo:latest

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Push Docker Image to ECR                  #add config
        run: |
          docker push 471112722662.dkr.ecr.us-east-1.amazonaws.com/bo:latest

      - name: Configure kubectl for EKS
        uses: aws-actions/amazon-eks-command@v1
        with:
          eks-command: update-kubeconfig
          cluster-name: bo-cluster

      - name: Deploy to AWS EKS
        run: |
          kubectl apply -f deployment.yaml
