name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Source Code Testing
        run: |
          # Run linting
          npm run lint          

      - name: Build Docker Image               #add config
        run: |
          docker build -t bo .
          docker tag bo:latest 471112722662.dkr.ecr.us-east-1.amazonaws.com/bo:latest

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR                  #add config
        run: |
          docker push 471112722662.dkr.ecr.us-east-1.amazonaws.com/bo:latest

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }} # Add config

      - name: Deploy to AWS EKS
        run: |
          kubectl apply -f deployment.yaml
